name: DCO

on:
  pull_request:
    branches: [ master ]

jobs:
  dco:
    runs-on: ubuntu-latest
    steps:
      - name: Check DCO
        uses: tim-actions/dco@master
        with:
          args: ""
